### ISSUE TITLE
Power Management: Shooter uses 45A current.

### ISSUE THREAD

**Issue by berkakinci** [FRCTEAM1474/2024RobotCode#11]
Current limit the shooter motor.
Here is the method for it:
https://codedocs.revrobotics.com/java/com/revrobotics/cansparkbase#setSmartCurrentLimit(int,int,int)

Also, here is an example to measure current from PDH:
https://github.com/REVrobotics/Power-Distribution-Hub-Examples/tree/c4c2a3dcf171485428f8c2f3694b1678c9d24bdb/Java/Get%20Current%20and%20Voltage/src/main/java/frc/robot

**Comment by FRCTEAM1474** [comment]
Should be fixed by #18

**Comment by berkakinci** [comment]
Closing.  We will do the enhancement of monitoring PDH currents later.  #19 for that.
